server:
  port: 8080
  context-path: /
spring:
  application:
    name: spring-boot-test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://xty-pc:3306/boot_security?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    filters: stat,wall
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 3000
    database: 1
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  thymeleaf:
    cache: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    excluded-view-names:
    template-resolver-order:
#mybatis:
  #configuration:
    #map-underscore-to-camel-case: true


logging:
  level:
    root: DEBUG